#Serie de Tiempo - Ejemplo

In [1]:
import numpy as np
import pandas as pd
date = pd.to_datetime("4th of July, 2015")
date = date + pd.to_timedelta(np.arange(30), 'D')
print(date)
x = np.random.randint(0,100,size=(len(date)))
df = pd.DataFrame(x, columns=['var'], index = date)
df['label'] = np.random.randint(35,163,size=(len(date)))
print(df.head())
len(df)
X = df.copy()

DatetimeIndex(['2015-07-04', '2015-07-05', '2015-07-06', '2015-07-07',
               '2015-07-08', '2015-07-09', '2015-07-10', '2015-07-11',
               '2015-07-12', '2015-07-13', '2015-07-14', '2015-07-15',
               '2015-07-16', '2015-07-17', '2015-07-18', '2015-07-19',
               '2015-07-20', '2015-07-21', '2015-07-22', '2015-07-23',
               '2015-07-24', '2015-07-25', '2015-07-26', '2015-07-27',
               '2015-07-28', '2015-07-29', '2015-07-30', '2015-07-31',
               '2015-08-01', '2015-08-02'],
              dtype='datetime64[ns]', freq=None)
            var  label
2015-07-04   95     69
2015-07-05   25     74
2015-07-06    0    105
2015-07-07   55    146
2015-07-08   64    104


#CV para Series de Tiempo sin Embargo

In [12]:
from sklearn.model_selection import TimeSeriesSplit

X = df.copy()
#X.head()

tss = TimeSeriesSplit(n_splits=5)



for train_index, test_index in tss.split(X):
    X_train, X_test = X['var'][:len(train_index)], X['var'][len(train_index): (len(train_index)+len(test_index))]
    y_train, y_test = X['label'][:len(train_index)], X['label'][len(train_index): (len(train_index)+len(test_index))]
    print(train_index)
    print(test_index)
  

[0 1 2 3 4]
[5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[20 21 22 23 24]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[25 26 27 28 29]


In [17]:
import numpy as np
from sklearn.model_selection import TimeSeriesSplit

tss = TimeSeriesSplit(n_splits=5)

X = df.copy()
X.head()
train = [] 
test = []

for train_index, test_index in tss.split(X):
    X_train2, X_test2 = X['var'][:int(len(train_index)*0.95)], X['var'][int(len(train_index)*1.04): (len(train_index)+len(test_index))]
    y_train2, y_test2 = X['label'][:int(len(train_index)*0.95)], X['label'][int(len(train_index)*1.04): (len(train_index)+len(test_index))]
    train.append(X_train2) 
    test.append(X_test2)

#CV K-Fold con embargo de 3 dias

In [11]:
#CV K-Fold con Embargo

from sklearn.model_selection import KFold

X = df.copy()

kf = KFold(n_splits=5)
train2 = [] 
test2 = []
indice_train = []
indice_test = []


for train, test in kf.split(X):
    #print(train)
    #print(test)
    train = list(train)
    lista = []
    # Embargo de 3 días
    #Si Test esta al inicio
    if test[0] == 0:
        del train[:3]
        X_train3, X_test3 = X['var'][train], X['var'][test]
        print(train)
        print(test)
        
    #Si test esta al final    
    elif test[-1] == len(X)-1:
        del train[-3:]
        X_train3, X_test3 = X['var'][train], X['var'][test]
        print(train)
        print(test)
        
    #Si test está en el medio    
    else:
        lista = list(range(test[0]-3,test[0]+1))
        lista.extend(list(range(test[-1]+1,test[-1]+4)))
        train = list(filter(lambda x: (x not in lista) , train))
        X_train3, X_test3 = X['var'][train], X['var'][test]
        print(train)
        print(test)


[9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
[0 1 2 3 4 5]
[0, 1, 2, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
[ 6  7  8  9 10 11]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 21, 22, 23, 24, 25, 26, 27, 28, 29]
[12 13 14 15 16 17]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 27, 28, 29]
[18 19 20 21 22 23]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[24 25 26 27 28 29]
